export const DummyIssues = [
  {
    IssueID: 123,
    StudentID: 1234,
    Date: "20 Jan, 2020",
    Desc: "ERP Portal not working",
    Likes: [1, 123],
    Comments: { studId: [123, 1232], comment: ["+1", "Facing the same issue"] },
    Tags: {
      Batch: [2018, 2019],
      Department: ["CSE", "CSD"],
      ConcernedDept: ["Academics"],
      Programme: [],
    },
    Archived: false,
    Resolved: true,
  },
  {
    IssueID: 123,
    StudentID: 1234,
    Desc: "Courses not showing up on ERP",
    Date: "22 Jan, 2018",
    Likes: [122, 2312, 3],
    Comments: { studId: [1232], comment: ["Facing the same issue"] },
    Tags: {
      Batch: [2018, 2019],
      Department: ["CSE", "CSD"],
      ConcernedDept: ["Academics"],
      Programme: [],
    },
    Archived: false,
    Resolved: true,
  },
  {
    IssueID: 123,
    StudentID: 1234,
    Date: "20 Feb, 2020",
    Desc: "Fee Portal not working",
    Likes: [122, 2312, 123, 12, 123],
    Comments: { studId: [123, 1232], comment: ["+1", "Facing the same issue"] },
    Tags: {
      Batch: [2018, 2019],
      Department: ["CSE", "CSD"],
      ConcernedDept: ["Academics"],
      Programme: [],
    },
    Archived: false,
    Resolved: true,
  },
  {
    IssueID: 123,
    StudentID: 1234,
    Date: "20 Feb, 2020",
    Desc: "Fee Portal not working",
    Likes: [122, 2312, 123, 12, 123],
    Comments: { studId: [123, 1232], comment: ["+1", "Facing the same issue"] },
    Tags: {
      Batch: [2018, 2019],
      Department: ["CSE", "CSD"],
      ConcernedDept: ["Academics"],
      Programme: ["B.Tech"],
    },
    Archived: false,
    Resolved: false,
  },
  {
    IssueID: 123,
    StudentID: 1234,
    Date: "20 Feb, 2020",
    Desc: "Fee Portal not working",
    Likes: [122, 2312, 123, 12, 123],
    Comments: { studId: [123, 1232], comment: ["+1", "Facing the same issue"] },
    Tags: {
      Batch: [2018, 2019],
      Department: ["CSE", "CSD"],
      Programme: ["B.Tech"],
    },
    Archived: false,
    Resolved: false,
  },
  {
    IssueID: 123,
    StudentID: 1234,
    Date: "20 Feb, 2020",
    Desc: "Fee Portal not working",
    Likes: [122, 2312, 123, 12, 123],
    Comments: { studId: [123, 1232], comment: ["+1", "Facing the same issue"] },
    Tags: {
      Batch: [2018, 2019],
      Department: ["CSE", "CSD"],
      ConcernedDept: ["Academics"],
      Programme: [],
    },
    Archived: false,
    Resolved: false,
  },
  {
    IssueID: 123,
    StudentID: 1234,
    Date: "20 Feb, 2020",
    Desc: "Fee Portal not working",
    Likes: [122, 2312, 123, 12, 123],
    Comments: { studId: [123, 1232], comment: ["+1", "Facing the same issue"] },
    Tags: {
      Batch: [2018, 2019],
      Department: ["CSE", "CSD"],
      ConcernedDept: ["Academics"],
      Programme: [],
    },
    Archived: false,
    Resolved: false,
  },
  {
    IssueID: 123,
    StudentID: 1234,
    Date: "20 Feb, 2020",
    Desc:
      "ERP doesn't have some courses. I couldn't find courses like SDOS, Machine Learning and computer Vision. \
                I am from 2018 batch CSE department. Others are facing the same issue. Please update the ERP",
    Likes: [122, 2312, 123, 12, 123],
    Comments: { studId: [123, 1232], comment: ["+1", "Facing the same issue"] },
    Tags: {
      Batch: [2018, 2019],
      Department: ["CSE", "CSD"],
      ConcernedDept: ["Academics"],
      Programme: [],
    },
    Archived: false,
    Resolved: false,
  },
];
